### ISSUE TITLE
Onboard Miatta

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#11]
- [x] Invited to Slack channels
- [x] Invited to GitHub repo 
- [x] Has reviewed README and Path Analysis report
- [x] Has reviewed RFQs for prior work
- [x] Met with Melissa for project intro

**Comment by Miatta18F** [comment]
I reviewed the RFQ and the Christmas Tree RFQ. Do you have Zahid's email address? I'd like to review the existing contracts. We may be able to use the BPA RFQ that you emailed me if the existing contracts can't be used. The BPA RFQ has 2 areas that development work may fall under (2.14.2 Application Development and 2.14.6 Application Software Management, Sustainment and Support).
