### ISSUE TITLE
Update 3rd-party contact info

### ISSUE THREAD

**Issue by mgwalker** [USDAForestService/USFS-timber-permitting#189]
Having a list of 3rd-party contacts is useful for long-term sustainability, so nobody has to just remember who to call or email. Currently that information is in the [Open Forest wiki](https://github.com/USDAForestService/fs-open-forest/wiki/Third-party-service-contacts).

It looks like most of the information is current and accurate but some observations:
- Is the NRM-SUDS integration still active? For some reason I've got it in my head that connection is no longer active but I'm not certain
- We should add an NRM-TIM contact
- We should add an FPFS contact

@mwreiss I suspect you know the answers off-hand. Do you know if Ming and Thompson the right points of contact for TIM and FPFS, respectively? If so, I can go update the wiki.

**Comment by mwreiss** [comment]
@mgwalker SUDS is still active, that handles all the MBS special uses permits.  

NRM-TIM  -- NRM Contact Ming  OF contact Shadat, Matt

FPFS -- Percy Lazarous   percy.lazarous@usda.gov  OF contact Shadat, Matt

**Comment by mgwalker** [comment]
That was really fast turnaround. Alrighty then. This one's done. 😆
