### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/USFS-timber-permitting#3]

**Comment by MelissaBraxton** [comment]
- [ ] Get access to staging site
- [ ] Added to GitHub repo w/ write access
- [ ] Review documentation (README, OF wiki, etc.)

**Comment by MelissaBraxton** [comment]
I'll follow up with you on how to get access to Open Forest staging.

**Comment by MelissaBraxton** [comment]
I'm hesitant to ask the OF folks for access if it's not 100% needed. With the video walkthrough we did on Friday, maybe we can check the first task off the list? @cmajel

**Comment by cmajel** [comment]
Sounds good - let's use the video to guide us for now. Will reopen if needed.
